# Pre-existing rule, not generated by detection-coverage.
# Fires when the poller logs an error. Says nothing about price plausibility,
# and cannot distinguish "no errors" from "not running".


def rule(event):
    return event.get("level") == "ERROR" and event.get("component") == "price-poller"


def title(event):
    return f"Price poller error: {event.get('message')}"
